[ignore]

glob = [
    # Ignore files and directories matching these glob patterns.
    # See https://docs.python.org/3/library/glob.html
    'docs/config/**',
    'docs/docker/**',
]
regex = [
    # Ignore files and directories matching these regex patterns.
    # See https://learnbyexample.github.io/python-regex-cheatsheet/
    # for example: regex = ['.*\.toml$']
    '.*\.yml$',
    '.*\.json$',
    '.*\.conf$',
    '.*\.pem$',
    '.*\.env$',
    '.*\.gz$',
    '.*\.SysConstant.java$'
]